%% Train a Double-DQN controller for the dynamic duopoly

clear;
clc;
close all;

thisFile = mfilename("fullpath");
rlDir = fileparts(thisFile);
modelDir = fullfile(fileparts(rlDir), "model");
addpath(modelDir);
addpath(rlDir);

rng(42);

%% Observation space: [x1; x2; demand]
obsInfo = rlNumericSpec([3 1]);
obsInfo.Name = "System States";
obsInfo.Description = "x1, x2, D(k)";

%% Discrete control space
actionValues = 0.55:0.05:1.65;
actionCells = num2cell(actionValues);
actInfo = rlFiniteSetSpec(actionCells);
actInfo.Name = "Firm 1 Control";

%% Function environment
env = rlFunctionEnv( ...
    obsInfo, ...
    actInfo, ...
    @rl_step_function, ...
    @rl_reset_function);

%% Q-network
network = [
    featureInputLayer(3)
    fullyConnectedLayer(64)
    reluLayer
    fullyConnectedLayer(64)
    reluLayer
    fullyConnectedLayer(numel(actionValues))
];

network = dlnetwork(network);

critic = rlVectorQValueFunction( ...
    network, ...
    getObservationInfo(env), ...
    getActionInfo(env));

optimizerOptions = rlOptimizerOptions( ...
    LearnRate=5e-3, ...
    GradientThreshold=1);

agentOptions = rlDQNAgentOptions( ...
    UseDoubleDQN=true, ...
    TargetUpdateMethod="periodic", ...
    TargetUpdateFrequency=4, ...
    ExperienceBufferLength=100000, ...
    DiscountFactor=0.98, ...
    MiniBatchSize=64, ...
    CriticOptimizerOptions=optimizerOptions);

agentOptions.EpsilonGreedyExploration.Epsilon = 1.0;
agentOptions.EpsilonGreedyExploration.EpsilonMin = 0.05;
agentOptions.EpsilonGreedyExploration.EpsilonDecay = 1e-4;

agent = rlDQNAgent( ...
    critic, ...
    agentOptions);

%% Training
trainingOptions = rlTrainingOptions( ...
    MaxEpisodes=1500, ...
    MaxStepsPerEpisode=24, ...
    Plots="training-progress", ...
    StopTrainingCriteria="AverageReward", ...
    StopTrainingValue=15000, ...
    UseParallel=false);

trainingStats = train( ...
    agent, ...
    env, ...
    trainingOptions);

%% Save trained workspace locally
outputPath = fullfile(rlDir, "trained_agent.mat");

save( ...
    outputPath, ...
    "agent", ...
    "env", ...
    "trainingStats");

fprintf("Saved trained agent to:\n%s\n", outputPath);
