%% Kalman Filter State Estimation
% Recursive state estimation for a noisy discrete-time linear system.
%
% Demonstrates:
%   - linear state-space simulation;
%   - prediction/update Kalman recursion;
%   - innovation and Kalman-gain computation;
%   - Joseph-form covariance update;
%   - comparison against an open-loop predictor;
%   - uncertainty-aware error visualization.
%
% Author: Alessandra D'Arienzo

clear;
clc;
close all;

rng(42, "twister");

%% 1. Model definition

T = 120;
dt = 1.0;

A = [1.0, dt;
     0.0, 0.90];

B = [0.0;
     1.0];

H = [1.0, 0.0];

% Process- and measurement-noise covariances.
Q = diag([0.05^2, 0.10^2]);
R = 0.80^2;

% Known deterministic input.
u = ones(1, T - 1);

%% 2. Allocate simulation and estimation arrays

xTrue = zeros(2, T);
measurement = zeros(1, T);

xFiltered = zeros(2, T);
xOpenLoop = zeros(2, T);

P = zeros(2, 2, T);
kalmanGain = zeros(2, T);
innovation = zeros(1, T);

% Deterministic initial true state.
xTrue(:,1) = [0.0; 0.5];

% Deliberately imperfect estimator initialization.
xFiltered(:,1) = [0.0; 0.0];
xOpenLoop(:,1) = xFiltered(:,1);

P(:,:,1) = eye(2);

measurement(1) = ...
    H * xTrue(:,1) + sqrt(R) * randn;

%% 3. Simulate the system and apply the Kalman filter

I = eye(2);
Lq = chol(Q, "lower");

for k = 2:T

    % ----- True system -----
    processNoise = Lq * randn(2,1);
    measurementNoise = sqrt(R) * randn;

    xTrue(:,k) = ...
        A * xTrue(:,k-1) + ...
        B * u(k-1) + ...
        processNoise;

    measurement(k) = ...
        H * xTrue(:,k) + ...
        measurementNoise;

    % ----- Open-loop benchmark -----
    xOpenLoop(:,k) = ...
        A * xOpenLoop(:,k-1) + ...
        B * u(k-1);

    % ----- Kalman prediction -----
    xPredicted = ...
        A * xFiltered(:,k-1) + ...
        B * u(k-1);

    PPredicted = ...
        A * P(:,:,k-1) * A' + Q;

    % ----- Innovation -----
    innovation(k) = ...
        measurement(k) - H * xPredicted;

    innovationVariance = ...
        H * PPredicted * H' + R;

    % ----- Kalman gain -----
    K = ...
        PPredicted * H' / innovationVariance;

    kalmanGain(:,k) = K;

    % ----- Measurement update -----
    xFiltered(:,k) = ...
        xPredicted + ...
        K * innovation(k);

    % Joseph-form covariance update.
    correction = I - K * H;

    P(:,:,k) = ...
        correction * PPredicted * correction' + ...
        K * R * K';
end

%% 4. Quantitative evaluation

filteredError = xTrue - xFiltered;
openLoopError = xTrue - xOpenLoop;

rmseFiltered = sqrt( ...
    mean(filteredError.^2, 2));

rmseOpenLoop = sqrt( ...
    mean(openLoopError.^2, 2));

fprintf("\n=== KALMAN FILTER RESULTS ===\n");
fprintf( ...
    "State 1 RMSE | filtered: %.4f | open-loop: %.4f\n", ...
    rmseFiltered(1), ...
    rmseOpenLoop(1));

fprintf( ...
    "State 2 RMSE | filtered: %.4f | open-loop: %.4f\n", ...
    rmseFiltered(2), ...
    rmseOpenLoop(2));

fprintf( ...
    "Innovation mean: %.4f\n", ...
    mean(innovation(2:end)));

fprintf( ...
    "Innovation std:  %.4f\n\n", ...
    std(innovation(2:end)));

%% 5. Visualization

time = 0:T-1;

scriptDir = fileparts(mfilename("fullpath"));
projectDir = fileparts(scriptDir);
resultsDir = fullfile(projectDir, "results");

if ~exist(resultsDir, "dir")
    mkdir(resultsDir);
end

figure("Position", [100 100 1000 700]);

tiledlayout(2,1, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");

nexttile;

plot( ...
    time, ...
    xTrue(1,:), ...
    "LineWidth", 1.7);

hold on;

scatter( ...
    time, ...
    measurement, ...
    12, ...
    "filled", ...
    "MarkerFaceAlpha", 0.25);

plot( ...
    time, ...
    xFiltered(1,:), ...
    "--", ...
    "LineWidth", 1.5);

grid on;

xlabel("Time step");
ylabel("State 1");

title("Measured State: True vs Noisy Observation vs Kalman Estimate");

legend( ...
    "True state", ...
    "Measurement", ...
    "Kalman estimate", ...
    "Location", "best");

nexttile;

plot( ...
    time, ...
    xTrue(2,:), ...
    "LineWidth", 1.7);

hold on;

plot( ...
    time, ...
    xFiltered(2,:), ...
    "--", ...
    "LineWidth", 1.5);

plot( ...
    time, ...
    xOpenLoop(2,:), ...
    ":", ...
    "LineWidth", 1.4);

grid on;

xlabel("Time step");
ylabel("State 2");

title("Hidden State Estimation");

legend( ...
    "True state", ...
    "Kalman estimate", ...
    "Open-loop predictor", ...
    "Location", "best");

exportgraphics( ...
    gcf, ...
    fullfile( ...
        resultsDir, ...
        "kalman_state_estimation.png"), ...
    "Resolution", 180);

%% 6. Error and uncertainty bands

sigmaState1 = squeeze( ...
    sqrt(P(1,1,:))).';

sigmaState2 = squeeze( ...
    sqrt(P(2,2,:))).';

figure("Position", [100 100 1000 700]);

tiledlayout(2,1, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");

nexttile;

plot( ...
    time, ...
    filteredError(1,:), ...
    "LineWidth", 1.3);

hold on;

plot( ...
    time, ...
    2 * sigmaState1, ...
    "--", ...
    "LineWidth", 1.0);

plot( ...
    time, ...
    -2 * sigmaState1, ...
    "--", ...
    "LineWidth", 1.0);

yline(0, ":");

grid on;

xlabel("Time step");
ylabel("Estimation error");

title("State 1 Error with ±2\sigma Bounds");

nexttile;

plot( ...
    time, ...
    filteredError(2,:), ...
    "LineWidth", 1.3);

hold on;

plot( ...
    time, ...
    2 * sigmaState2, ...
    "--", ...
    "LineWidth", 1.0);

plot( ...
    time, ...
    -2 * sigmaState2, ...
    "--", ...
    "LineWidth", 1.0);

yline(0, ":");

grid on;

xlabel("Time step");
ylabel("Estimation error");

title("State 2 Error with ±2\sigma Bounds");

exportgraphics( ...
    gcf, ...
    fullfile( ...
        resultsDir, ...
        "kalman_error_bounds.png"), ...
    "Resolution", 180);
