%% Markowitz Mean-Variance Portfolio Optimization
% Long-only efficient frontier using convex quadratic programming.
%
% Demonstrates:
%   - covariance-matrix validation;
%   - global minimum-variance optimization;
%   - efficient-frontier construction;
%   - equality-constrained target-return portfolios;
%   - equal-weight and maximum-Sharpe benchmarks;
%   - portfolio-weight interpretation.
%
% Synthetic numerical inputs are used for methodology demonstration only.
%
% Author: Alessandra D'Arienzo

clear;
clc;
close all;

%% 1. Synthetic asset assumptions

assetNames = [ ...
    "Asset A", ...
    "Asset B", ...
    "Asset C", ...
    "Asset D"];

mu = [ ...
    0.10;
    0.12;
    0.07;
    0.15];

Sigma = [ ...
    0.010, 0.002, 0.001, 0.003;
    0.002, 0.015, 0.002, 0.004;
    0.001, 0.002, 0.008, 0.002;
    0.003, 0.004, 0.002, 0.020];

riskFreeRate = 0.02;

nAssets = numel(mu);

%% 2. Input validation

if ~isequal(size(Sigma), [nAssets nAssets])
    error( ...
        "Covariance matrix dimensions do not match expected returns.");
end

% Enforce numerical symmetry.
Sigma = 0.5 * (Sigma + Sigma');

eigenvalues = eig(Sigma);

if any(eigenvalues < -1e-10)
    error( ...
        "Covariance matrix must be positive semidefinite.");
end

if any(~isfinite(mu)) || any(~isfinite(Sigma), "all")
    error("Expected returns and covariance matrix must be finite.");
end

%% 3. Optimization setup

% quadprog minimizes:
%
%   0.5 * w' H w + f' w
%
% therefore H = 2*Sigma gives portfolio variance w'*Sigma*w.
Hqp = 2 * Sigma;
fqp = zeros(nAssets,1);

lb = zeros(nAssets,1);
ub = ones(nAssets,1);

fullyInvestedAeq = ones(1, nAssets);
fullyInvestedBeq = 1;

options = optimoptions( ...
    "quadprog", ...
    "Display", "off", ...
    "Algorithm", "interior-point-convex");

%% 4. Global minimum-variance portfolio

[wGMV, ~, exitflagGMV] = quadprog( ...
    Hqp, ...
    fqp, ...
    [], ...
    [], ...
    fullyInvestedAeq, ...
    fullyInvestedBeq, ...
    lb, ...
    ub, ...
    [], ...
    options);

if exitflagGMV <= 0
    error("Global minimum-variance optimization did not converge.");
end

returnGMV = mu' * wGMV;
riskGMV = sqrt(wGMV' * Sigma * wGMV);

%% 5. Efficient frontier

maxFeasibleReturn = max(mu);

nFrontier = 60;

targetReturns = linspace( ...
    returnGMV, ...
    maxFeasibleReturn, ...
    nFrontier);

frontierReturns = nan(1, nFrontier);
frontierRisks = nan(1, nFrontier);
frontierWeights = nan(nAssets, nFrontier);

for i = 1:nFrontier

    target = targetReturns(i);

    Aeq = [ ...
        ones(1, nAssets);
        mu'];

    beq = [ ...
        1;
        target];

    [w, ~, exitflag] = quadprog( ...
        Hqp, ...
        fqp, ...
        [], ...
        [], ...
        Aeq, ...
        beq, ...
        lb, ...
        ub, ...
        [], ...
        options);

    if exitflag <= 0
        continue;
    end

    frontierWeights(:,i) = w;

    frontierReturns(i) = mu' * w;

    frontierRisks(i) = sqrt( ...
        w' * Sigma * w);
end

valid = ...
    isfinite(frontierReturns) & ...
    isfinite(frontierRisks);

frontierReturns = frontierReturns(valid);
frontierRisks = frontierRisks(valid);
frontierWeights = frontierWeights(:,valid);

%% 6. Equal-weight benchmark

wEqual = ones(nAssets,1) / nAssets;

returnEqual = mu' * wEqual;
riskEqual = sqrt( ...
    wEqual' * Sigma * wEqual);

%% 7. Maximum-Sharpe portfolio on the discretized frontier

sharpe = ...
    (frontierReturns - riskFreeRate) ./ ...
    frontierRisks;

[~, idxMaxSharpe] = max(sharpe);

wMaxSharpe = frontierWeights(:,idxMaxSharpe);
returnMaxSharpe = frontierReturns(idxMaxSharpe);
riskMaxSharpe = frontierRisks(idxMaxSharpe);
maxSharpe = sharpe(idxMaxSharpe);

%% 8. Numerical summary

fprintf("\n=== MARKOWITZ RESULTS ===\n");

fprintf( ...
    "Global minimum-variance portfolio\n");

fprintf( ...
    "  Expected return: %.4f\n", ...
    returnGMV);

fprintf( ...
    "  Volatility:      %.4f\n", ...
    riskGMV);

fprintf( ...
    "\nMaximum-Sharpe frontier portfolio\n");

fprintf( ...
    "  Expected return: %.4f\n", ...
    returnMaxSharpe);

fprintf( ...
    "  Volatility:      %.4f\n", ...
    riskMaxSharpe);

fprintf( ...
    "  Sharpe ratio:    %.4f\n\n", ...
    maxSharpe);

summaryTable = table( ...
    assetNames', ...
    wGMV, ...
    wMaxSharpe, ...
    wEqual, ...
    "VariableNames", { ...
        "Asset", ...
        "GMVWeight", ...
        "MaxSharpeWeight", ...
        "EqualWeight"});

disp(summaryTable);

%% 9. Efficient-frontier visualization

scriptDir = fileparts(mfilename("fullpath"));
projectDir = fileparts(scriptDir);
resultsDir = fullfile(projectDir, "results");

if ~exist(resultsDir, "dir")
    mkdir(resultsDir);
end

figure("Position", [100 100 950 650]);

plot( ...
    frontierRisks, ...
    frontierReturns, ...
    "LineWidth", 2.0);

hold on;

scatter( ...
    riskGMV, ...
    returnGMV, ...
    90, ...
    "filled");

scatter( ...
    riskMaxSharpe, ...
    returnMaxSharpe, ...
    90, ...
    "filled");

scatter( ...
    riskEqual, ...
    returnEqual, ...
    90, ...
    "filled");

grid on;

xlabel("Portfolio volatility");
ylabel("Expected return");

title("Markowitz Efficient Frontier");

legend( ...
    "Efficient frontier", ...
    "Global minimum variance", ...
    "Maximum Sharpe", ...
    "Equal weight", ...
    "Location", "best");

exportgraphics( ...
    gcf, ...
    fullfile( ...
        resultsDir, ...
        "markowitz_efficient_frontier.png"), ...
    "Resolution", 180);

%% 10. Portfolio composition along the frontier

figure("Position", [100 100 950 650]);

area( ...
    frontierReturns, ...
    frontierWeights');

grid on;

xlabel("Target expected return");
ylabel("Portfolio weight");

title("Asset Allocation Along the Efficient Frontier");

legend( ...
    assetNames, ...
    "Location", "eastoutside");

ylim([0 1]);

exportgraphics( ...
    gcf, ...
    fullfile( ...
        resultsDir, ...
        "markowitz_frontier_weights.png"), ...
    "Resolution", 180);
