function J = nmpc_cost( ...
    controlSequence, ...
    x0, ...
    k0, ...
    Ts, ...
    nSteps, ...
    mismatchWeight, ...
    controlWeight, ...
    shapingWeight, ...
    uMin, ...
    uMax, ...
    demandMin, ...
    demandMax)
%NMPC_COST Finite-horizon nonlinear economic-control objective.
%
% The full nonlinear duopoly is simulated over the candidate control
% sequence. The cost mirrors the economic structure used in the project:
%
%   - maximize firm-1 profit;
%   - reduce Q-D mismatch;
%   - regularize the control;
%   - encourage demand-responsive control;
%   - penalize infeasible states and negative profits.

    xk = x0;
    k = k0;
    J = 0.0;

    horizon = numel(controlSequence);

    for idx = 1:horizon

        Dk = ...
            0.9425 + ...
            0.3575 * sin(2*pi*(k - 13)/nSteps);

        u = controlSequence(idx);

        [~, trajectory] = ode45( ...
            @(t,x) duopoly_dynamics(t, x, u, Dk), ...
            [0 Ts], ...
            xk);

        xNext = trajectory(end,:).';

        x1 = xNext(1);
        x2 = xNext(2);
        totalProduction = x1 + x2;

        price = Dk / max(totalProduction, 1e-6);
        profit1 = (price - u) * x1;

        %% Economic objective
        costProfit = -profit1;

        mismatch = totalProduction - Dk;
        costMismatch = ...
            mismatchWeight * mismatch^2;

        costControl = ...
            controlWeight * u^2;

        demandNormalized = ...
            (Dk - demandMin) / ...
            (demandMax - demandMin);

        demandNormalized = min( ...
            max(demandNormalized, 0), ...
            1);

        referenceControl = ...
            uMax - ...
            (uMax - uMin) * demandNormalized;

        costShape = ...
            shapingWeight * ...
            (u - referenceControl)^2;

        %% Feasibility
        negativeStateViolation = max(0, -xNext);
        violationNorm = norm(negativeStateViolation);

        costState = ...
            500 * violationNorm^2;

        if profit1 < 0
            costNegativeProfit = abs(profit1)^2;
        else
            costNegativeProfit = 0;
        end

        J = J + ...
            costProfit + ...
            costMismatch + ...
            costControl + ...
            costShape + ...
            costState + ...
            costNegativeProfit;

        xk = xNext;
        k = k + 1;
    end
end
